page_blocks: []
_array_structures:
  content-blocks:
    values:
      - label: Hero
        icon: star
        value:
          _section-type: hero
          link:
            description: If you would like that awesome scroll feature that happens when someone clicks on a link in the navigation, then you'll need to add a page id. The page id can be added in the below box labeled "link". Your id is a short word describing the section it is leading to. For example- about.
            link:
          hero_image:
          hero:
      - label: Image and Textarea
        icon: image
        value:
          _section-type: image-and-textarea
          link:
            description: If you would like that awesome scroll feature that happens when someone clicks on a link in the navigation, then you'll need to add a page id. The page id can be added in the below box labeled "link". Your id is a short word describing the section it is leading to. For example- about.
            link:
          image:
          tablet_images:
            top_image:
            bottom_image:
          heading:
          textarea:
      - label: Projects
        icon: work
        value:
          _section-type: projects
          link:
            description: If you would like that awesome scroll feature that happens when someone clicks on a link in the navigation, then you'll need to add a page id. The page id can be added in the below box labeled "link". Your id is a short word describing the section it is leading to. For example- about.
            link:
          heading:
          first-project:
            image:
            subheading:
            textarea:
          second-project:
            image:
            subheading:
            textarea:
          third-project:
            image:
            subheading:
            textarea:
      - label: Carousel
        icon: money
        value:
          _section-type: carousel
          link:
            description: If you would like that awesome scroll feature that happens when someone clicks on a link in the navigation, then you'll need to add a page id. The page id can be added in the below box labeled "link". Your id is a short word describing the section it is leading to. For example- about.
            link:
          heading:
          carousel:
            textarea:
            symbols:
            ending:
      - label: Form
        icon: article
        value:
          _section-type: form
          link:
            description:  If you would like that awesome scroll feature that happens when someone clicks on a link in the navigation, then you'll need to add a page id. The page id can be added in the below box labeled "link". Your id is a short word describing the section it is leading to. For example- about.
            link:
          heading:
          top:
            vertical-subheading:
            text-option-1:
            text-option-2:
            text-option-3:
          bottom:
            vertical-subheading:
            message:
          option-box:
            subheading:
            option-1:
            option-2:
            option-3:
            option-4:
hero-font:
_select_data:
  fonts:
      - Amatic SC, cursive
      - Barlow Condensed, sans-serif
      - Belleza, sans-serif
      - Kaushan Script, cursive
      - Montserrat, sans-serif
      - Oooh Baby, cursive
      - Playfair Display, serif
      - Poppins, sans-serif
      - Quicksand, sans-serif
      - Raleway, sans-serif
      - Roboto, sans-serif
headings-font:
_select_data:
  fonts:
      - Amatic SC, cursive
      - Barlow Condensed, sans-serif
      - Belleza, sans-serif
      - Kaushan Script, cursive
      - Montserrat, sans-serif
      - Oooh Baby, cursive
      - Playfair Display, serif
      - Poppins, sans-serif
      - Quicksand, sans-serif
      - Raleway, sans-serif
      - Roboto, sans-serif
subheadings-font:
_select_data:
  fonts:
      - Amatic SC, cursive
      - Barlow Condensed, sans-serif
      - Belleza, sans-serif
      - Kaushan Script, cursive
      - Montserrat, sans-serif
      - Oooh Baby, cursive
      - Playfair Display, serif
      - Poppins, sans-serif
      - Quicksand, sans-serif
      - Raleway, sans-serif
      - Roboto, sans-serif
text-font:
_select_data:
  fonts:
      - Amatic SC, cursive
      - Barlow Condensed, sans-serif
      - Belleza, sans-serif
      - Kaushan Script, cursive
      - Montserrat, sans-serif
      - Oooh Baby, cursive
      - Playfair Display, serif
      - Poppins, sans-serif
      - Quicksand, sans-serif
      - Raleway, sans-serif
      - Roboto, sans-serif
