page_blocks: []
_array_structures:
  content-block:
    values:
      - label: banner image
        icon: star
        value:
          _section-type: banner_image
          banner_image:
          hero:
      - label: arched image with text
        icon: image
        value:
          _section-type: arched-image-with-text
          arched_image:
          heading:
          text:
      - label: projects
        icon: work
        value:
          _section-type: projects
          hero:
          first-project.image:
          first-project.subheader:
          first-project.text:
          second-project.image:
          second-project.subheader:
          second-project.text:
          third-project.image:
          third-project.subheader:
          third-project.text:
