page_blocks: []
_array_structures:
  content-blocks:
    values:
      - label: Hero
        icon: star
        value:
          _section-type: hero
          hero_image:
          hero:
      - label: Image and Text
        icon: image
        value:
          _section-type: image-and-text
          image:
          heading:
          text:
      - label: Projects
        icon: work
        value:
          _section-type: projects
          heading:
          first-project:
            image:
            subheading:
            text:
          second-project:
            image:
            subheading:
            text:
          third-project:
            image:
            subheading:
            text:
      - label: Carousel
        icon: money
        value:
          _section-type: carousel
          heading:
          carousel:
          - text:
            symbols:
            ending:
      - label: Form
        icon: article
        value:
          _section-type: form
          heading:
          top:
            vertical-subheading:
            text-option-1:
            text-option-2:
            text-option-3:
          bottom:
            vertical-subheading:
            message:
          option-box:
            subheading:
            option-1:
            option-2:
            option-3:
            option-4:
hero-font:
_select_data:
  fonts:
      - Amatic SC
      - Barlow Condensed
      - Belleza
      - Kaushan Script
      - Montserrat
      - Oooh Baby
      - Playfair Display
      - Poppins
      - Quicksand
      - Raleway
      - Roboto
heading-font:
_select_data:
  fonts:
      - Amatic SC
      - Barlow Condensed
      - Belleza
      - Kaushan Script
      - Montserrat
      - Oooh Baby
      - Playfair Display
      - Poppins
      - Quicksand
      - Raleway
      - Roboto
sunheading-font:
_select_data:
  fonts:
      - 'Amatic SC', cursive
      - 'Barlow Condensed', sans-serif
      - 'Belleza', sans-serif
      - 'Kaushan Script', cursive
      - 'Montserrat', sans-serif
      - 'Oooh Baby', cursive
      - 'Playfair Display', serif
      - 'Poppins', sans-serif
      - 'Quicksand', sans-serif
      - 'Raleway', sans-serif
      - 'Roboto', sans-serif
text-font:
_select_data:
  fonts:
      - Amatic SC
      - Barlow Condensed
      - Belleza
      - Kaushan Script
      - Montserrat
      - Oooh Baby
      - Playfair Display
      - Poppins
      - Quicksand
      - Raleway
      - Roboto
