page_blocks: []
_array_structures:
  content-block:
    values:
      - label: banner image
        icon: star
        value:
          _section-type: banner_image
          banner_image:
          hero:
      - label: arched image with text
        icon: image
        value:
          _section-type: arched-image-with-text
          arched_image:
          heading:
          text:
      - label: projects
        icon: work
        value:
          _section-type: projects
          hero:
          project.first_image:
          first-subheader:
          first-text:
          second_image:
          second-subheader:
          second-text:
          third_image:
          third-subheader:
          third-text:
